name: Nightly Blog Post Generator

on:
  schedule:
    - cron: '0 0 * * *'   # 8 PM EDT
    - cron: '0 1 * * *'   # 8 PM EST
  workflow_dispatch:      # Allow manual triggering

jobs:
  nightly-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Generate blog post
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: python agents/pipeline.py 